version: "2"
run:
  concurrency: 4
  go: "1.20"
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - dogsled
    - dupl
    - durationcheck
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 800
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - commentedOutCode
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 80
        rangeExprCopy:
          sizeThreshold: 512
        rangeValCopy:
          sizeThreshold: 128
    gocyclo:
      min-complexity: 20
    godot:
      scope: declarations
      capital: false
    gosec:
      excludes:
        - G112
        - G401
        - G501
        - G601
      config:
        G101:
          pattern: (?i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer|cred|crt|cert|certificate
        nosec: true
    nestif:
      min-complexity: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: pkg
      - linters:
          - revive
        path: cmd
    paths:
      - test/
      - hack
      - vendor
      - api/vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/kubean-io/kubean
  exclusions:
    generated: lax
    paths:
      - test/
      - hack
      - vendor
      - api/vendor
      - third_party$
      - builtin$
      - examples$
