// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubean-io/kubean-api/apis/clusteroperation/v1alpha1"
	clusteroperationv1alpha1 "github.com/kubean-io/kubean-api/client/applyconfiguration/clusteroperation/v1alpha1"
	typedclusteroperationv1alpha1 "github.com/kubean-io/kubean-api/client/clientset/versioned/typed/clusteroperation/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterOperations implements ClusterOperationInterface
type fakeClusterOperations struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterOperation, *v1alpha1.ClusterOperationList, *clusteroperationv1alpha1.ClusterOperationApplyConfiguration]
	Fake *FakeClusterOperationV1alpha1
}

func newFakeClusterOperations(fake *FakeClusterOperationV1alpha1) typedclusteroperationv1alpha1.ClusterOperationInterface {
	return &fakeClusterOperations{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterOperation, *v1alpha1.ClusterOperationList, *clusteroperationv1alpha1.ClusterOperationApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusteroperations"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterOperation"),
			func() *v1alpha1.ClusterOperation { return &v1alpha1.ClusterOperation{} },
			func() *v1alpha1.ClusterOperationList { return &v1alpha1.ClusterOperationList{} },
			func(dst, src *v1alpha1.ClusterOperationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterOperationList) []*v1alpha1.ClusterOperation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterOperationList, items []*v1alpha1.ClusterOperation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
