// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clusteroperationv1alpha1 "github.com/kubean-io/kubean-api/apis/clusteroperation/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterOperationLister helps list ClusterOperations.
// All objects returned here must be treated as read-only.
type ClusterOperationLister interface {
	// List lists all ClusterOperations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clusteroperationv1alpha1.ClusterOperation, err error)
	// Get retrieves the ClusterOperation from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clusteroperationv1alpha1.ClusterOperation, error)
	ClusterOperationListerExpansion
}

// clusterOperationLister implements the ClusterOperationLister interface.
type clusterOperationLister struct {
	listers.ResourceIndexer[*clusteroperationv1alpha1.ClusterOperation]
}

// NewClusterOperationLister returns a new ClusterOperationLister.
func NewClusterOperationLister(indexer cache.Indexer) ClusterOperationLister {
	return &clusterOperationLister{listers.New[*clusteroperationv1alpha1.ClusterOperation](indexer, clusteroperationv1alpha1.Resource("clusteroperation"))}
}
