// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	manifestv1alpha1 "github.com/kubean-io/kubean-api/apis/manifest/v1alpha1"
	applyconfigurationmanifestv1alpha1 "github.com/kubean-io/kubean-api/client/applyconfiguration/manifest/v1alpha1"
	scheme "github.com/kubean-io/kubean-api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ManifestsGetter has a method to return a ManifestInterface.
// A group's client should implement this interface.
type ManifestsGetter interface {
	Manifests() ManifestInterface
}

// ManifestInterface has methods to work with Manifest resources.
type ManifestInterface interface {
	Create(ctx context.Context, manifest *manifestv1alpha1.Manifest, opts v1.CreateOptions) (*manifestv1alpha1.Manifest, error)
	Update(ctx context.Context, manifest *manifestv1alpha1.Manifest, opts v1.UpdateOptions) (*manifestv1alpha1.Manifest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, manifest *manifestv1alpha1.Manifest, opts v1.UpdateOptions) (*manifestv1alpha1.Manifest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*manifestv1alpha1.Manifest, error)
	List(ctx context.Context, opts v1.ListOptions) (*manifestv1alpha1.ManifestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *manifestv1alpha1.Manifest, err error)
	Apply(ctx context.Context, manifest *applyconfigurationmanifestv1alpha1.ManifestApplyConfiguration, opts v1.ApplyOptions) (result *manifestv1alpha1.Manifest, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, manifest *applyconfigurationmanifestv1alpha1.ManifestApplyConfiguration, opts v1.ApplyOptions) (result *manifestv1alpha1.Manifest, err error)
	ManifestExpansion
}

// manifests implements ManifestInterface
type manifests struct {
	*gentype.ClientWithListAndApply[*manifestv1alpha1.Manifest, *manifestv1alpha1.ManifestList, *applyconfigurationmanifestv1alpha1.ManifestApplyConfiguration]
}

// newManifests returns a Manifests
func newManifests(c *ManifestV1alpha1Client) *manifests {
	return &manifests{
		gentype.NewClientWithListAndApply[*manifestv1alpha1.Manifest, *manifestv1alpha1.ManifestList, *applyconfigurationmanifestv1alpha1.ManifestApplyConfiguration](
			"manifests",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *manifestv1alpha1.Manifest { return &manifestv1alpha1.Manifest{} },
			func() *manifestv1alpha1.ManifestList { return &manifestv1alpha1.ManifestList{} },
		),
	}
}
