// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	manifestv1alpha1 "github.com/kubean-io/kubean-api/apis/manifest/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ManifestLister helps list Manifests.
// All objects returned here must be treated as read-only.
type ManifestLister interface {
	// List lists all Manifests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*manifestv1alpha1.Manifest, err error)
	// Get retrieves the Manifest from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*manifestv1alpha1.Manifest, error)
	ManifestListerExpansion
}

// manifestLister implements the ManifestLister interface.
type manifestLister struct {
	listers.ResourceIndexer[*manifestv1alpha1.Manifest]
}

// NewManifestLister returns a new ManifestLister.
func NewManifestLister(indexer cache.Indexer) ManifestLister {
	return &manifestLister{listers.New[*manifestv1alpha1.Manifest](indexer, manifestv1alpha1.Resource("manifest"))}
}
