# Copyright 2023 Authors of kubean-io
# SPDX-License-Identifier: Apache-2.0

---
- name: Pre-check
  hosts: k8s_cluster,etcd
  gather_facts: false
  become: true
  vars:
    check_connection: true
    fetch_os_type: true
    fetch_os_kernel_version: true
    check_existing_k8s_service: true
    check_existing_docker: true
    check_dual_stack_network: true
    check_node_time_sync: true

  tasks:
    - name: Gather minimal facts
      setup:
        gather_subset: '!all,!min,architecture,os_family,pkg_mgr'
        gather_timeout: 5

    - name: Perform check_connection
      ansible.builtin.ping:
      register: connection_ping_result
      ignore_errors: true
      when:
        - check_connection
    - name: Process connection_ping_result
      ignore_errors: true
      set_fact:
        check_connection_result: "{{ connection_ping_result.failed == false }}"
      when:
        - check_connection
    - name: Store check_connection result to localhost
      shell: " ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )  ; yq -i '.{{inventory_hostname}}.ping_connection=\"{{ check_connection_result }}\"' /tmp/kubean_data_temp_cache_{{inventory_hostname}} "
      delegate_to: localhost
      when:
        - check_connection

    - name: Perform fetch_os_type
      shell: cat /etc/os-release
      register: os_release_cmd_result
      ignore_errors: true
      when:
        - fetch_os_type
    - name: Process fetch_os_type_result
      ignore_errors: true
      set_fact:
        ## fetch_os_type_result: "{{ dict(_keys|zip(_vals)) | combine( { 'RAW_OUTPUT': os_release_cmd_result.stdout } ) }}" ## RAW_OUTPUT.value does not work well with `yq`.
        fetch_os_type_result: "{{ dict(_keys|zip(_vals)) }}"
      vars:
        _arr: "{{ os_release_cmd_result.stdout.splitlines() | map('trim') | select() | list }}"
        _keys: "{{ _arr | map('split', '=') | map('first') | map('replace', '\"' ,'') | map('trim') | list }}"
        _vals: "{{ _arr | map('split', '=') | map('last') | map('replace', '\"' , '') | map('trim') | list }}"
      when:
        - fetch_os_type
    - name: Store fetch_os_type result to localhost
      shell: |-
        ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi );
        {%- for key, value in fetch_os_type_result.items() %}
        yq -i '.{{inventory_hostname}}.os_type.{{ key }}="{{ value }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}};
        {%- endfor %}
      delegate_to: localhost
      when:
        - fetch_os_type


    - name: Perform check_existing_k8s_service
      shell: bash -c "kubectl get namespace >/dev/null 2>&1 " || bash -c " ps -ef | grep kubelet | grep -v grep >/dev/null 2>&1 "
      register: check_k8s_cmd_result
      ignore_errors: true
      when:
        - check_existing_k8s_service
    - name: Process check_k8s_cmd_result
      ignore_errors: true
      set_fact:
        check_existing_k8s_service_result: "{{ check_k8s_cmd_result.rc == 0 }}"
      when:
        - check_existing_k8s_service
    - name: Store check_existing_k8s_service result to localhost
      shell: " ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )  ; yq -i '.{{inventory_hostname}}.existing_k8s_service=\"{{ check_existing_k8s_service_result }}\"' /tmp/kubean_data_temp_cache_{{inventory_hostname}} "
      delegate_to: localhost
      when:
        - check_existing_k8s_service

    - name: Perform check_existing_docker
      when: check_existing_docker
      block:
        - name: Check existing dockerd  
          shell: "ps -eo comm= | grep -q dockerd"
          register: check_docker_cmd_result
          ignore_errors: true
        - name: Store result to localhost
          shell: " ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )  ; yq -i '.{{inventory_hostname}}.existing_docker=\"{{ check_docker_cmd_result.rc == 0 }}\"' /tmp/kubean_data_temp_cache_{{inventory_hostname}} "
          delegate_to: localhost

    - name: Perform fetch time info
      shell: date +%s
      register: timestamp_result
      ignore_errors: true
      when:
        - check_node_time_sync

    - name: Perform fetch timezone
      shell: timedatectl | grep "Time zone"
      register: timezone_result
      ignore_errors: true
      when:
        - check_node_time_sync

    - name: Perform fetch ip info
      shell: |
        ip --brief  address show | grep -i up | grep '{{ access_ip }}' | sed 's/fe80\S*//g' | sed 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\S*//g' | head
      register: ip_cmd_info_result # ens192       UP         fd00:10:7::103/64
      ignore_errors: true
      when:
        - check_dual_stack_network
    - name: Store dual_stack_network result
      shell: |
        ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )
        yq -i '.{{inventory_hostname}}.dual_stack_network="{{ ip_cmd_info_result.stdout | split | length > 2 }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
      delegate_to: localhost
      ignore_errors: true
      when:
        - check_dual_stack_network

    - name: Store os_kernel_version result to localhost
      shell: |
        ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )
        yq -i '.{{inventory_hostname}}.os_kernel_version_output="{{ ansible_kernel }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
        yq -i '.{{inventory_hostname}}.os_kernel_version="{{ ansible_kernel.split('-')[0] }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
        yq -i '.{{inventory_hostname}}.pkg_mgr="{{ ansible_pkg_mgr }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
      ignore_errors: true
      delegate_to: localhost
      when:
        - fetch_os_kernel_version

    - name: Store os family result to localhost
      shell: |
        ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )
        yq -i '.{{inventory_hostname}}.os_family="{{ ansible_os_family }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
      ignore_errors: true
      delegate_to: localhost

    - name: Store instruction set architecture result to localhost
      shell: |
        ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )
        yq -i '.{{inventory_hostname}}.architecture="{{ ansible_architecture }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
      ignore_errors: true
      delegate_to: localhost

    - name: Store node time info to localhost
      shell: |
        ( if [ ! -f /tmp/kubean_data_temp_cache_{{inventory_hostname}} ]; then touch /tmp/kubean_data_temp_cache_{{inventory_hostname}} ; fi )
        yq -i '.{{inventory_hostname}}.node_timestamp="{{ timestamp_result.stdout }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
        yq -i '.{{inventory_hostname}}.timezone="{{ timezone_result.stdout.split(':')[1].strip() }}"' /tmp/kubean_data_temp_cache_{{inventory_hostname}}
      ignore_errors: true
      delegate_to: localhost
      when:
        - check_node_time_sync

- import_playbook: check-kernel-compatibility.yml

- hosts: localhost
  gather_facts: false
  vars:
    cluster_name: "{{ lookup('env','CLUSTER_NAME') }}"
    configmap_name: "{{ cluster_name }}-precheck-result"
    spray_job_pod_namespace: 'kubean-system'
  tasks:
    - name: Try to Fetch Spray Job Pod Namespace
      shell: 'cat /run/secrets/kubernetes.io/serviceaccount/namespace'
      ignore_errors: true
      register: namespace_content

    - name: Update Spray Job Pod Namespace
      set_fact:
        spray_job_pod_namespace: "{{ namespace_content.stdout | trim }}"
      when: namespace_content.rc == 0

    - name: Get precheck result
      shell: |
        cat /tmp/kubean_data_temp_cache_* > /tmp/kubean_data_temp_cache
        yq -o=json /tmp/kubean_data_temp_cache || echo {}
      register: yq_cmd
      ignore_errors: true

    - name: Set precheck result
      set_fact:
        check_result: "{{yq_cmd.stdout | replace('\"True\"','true') | replace('\"False\"','false')}}"

    - name: Show precheck result
      debug: var=check_result

    - name: Clean configmap
      shell: "/usr/local/bin/kubectl -n {{ spray_job_pod_namespace }} delete configmap {{ configmap_name }} --ignore-not-found --timeout=2s"
      args:
        executable: /bin/bash
      ignore_errors: true
      register: clean_cm_result
      until: clean_cm_result.rc == 0
      retries: 3
      delay: 2
      when: namespace_content.rc == 0

    - name: Create configmap
      shell: "/usr/local/bin/kubectl -n {{ spray_job_pod_namespace }} create configmap {{ configmap_name }} --from-file=/tmp/kubean_data_temp_cache "
      args:
        executable: /bin/bash
      register: create_cm_result
      until: create_cm_result.rc == 0
      retries: 5
      delay: 5
      ignore_errors: true
      when: namespace_content.rc == 0

    - name: Patch preCheckResultRef info
      shell: >
        /usr/local/bin/kubectl patch --type=merge clusters.kubean.io {{ cluster_name }} -p '{"spec": {"preCheckRef": {"name": "'{{ configmap_name }}'", "namespace": "'{{ spray_job_pod_namespace }}'"}}}'
      args:
        executable: /bin/bash
      register: patch_ref_result
      until: patch_ref_result.rc == 0
      retries: 5
      delay: 5
      ignore_errors: true
      when: namespace_content.rc == 0
