---
- name: Update Kylin version identifier
  hosts: k8s_cluster:etcd:calico_rr
  gather_facts: false
  tasks:
    - name: Gather necessary facts (distribution)
      ansible.builtin.setup:
        gather_subset: '!all,!min,distribution,distribution_major_version,distribution_version'

    - name: Strip "V" prefix
      ansible.builtin.lineinfile:
        path: /etc/os-release
        regex: '^VERSION_ID="V'
        line: 'VERSION_ID="{{ ansible_distribution_version | regex_replace("^V", "") }}"'
      when:
        - ansible_distribution == "Kylin Linux Advanced Server"
        - ansible_distribution_major_version == "V10"