// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HostsMapApplyConfiguration represents a declarative configuration of the HostsMap type for use
// with apply.
type HostsMapApplyConfiguration struct {
	Domain  *string `json:"domain,omitempty"`
	Address *string `json:"address,omitempty"`
}

// HostsMapApplyConfiguration constructs a declarative configuration of the HostsMap type for use with
// apply.
func HostsMap() *HostsMapApplyConfiguration {
	return &HostsMapApplyConfiguration{}
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *HostsMapApplyConfiguration) WithDomain(value string) *HostsMapApplyConfiguration {
	b.Domain = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *HostsMapApplyConfiguration) WithAddress(value string) *HostsMapApplyConfiguration {
	b.Address = &value
	return b
}
