// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// StatusApplyConfiguration represents a declarative configuration of the Status type for use
// with apply.
type StatusApplyConfiguration struct {
	LocalAvailable *LocalAvailableApplyConfiguration `json:"localAvailable,omitempty"`
}

// StatusApplyConfiguration constructs a declarative configuration of the Status type for use with
// apply.
func Status() *StatusApplyConfiguration {
	return &StatusApplyConfiguration{}
}

// WithLocalAvailable sets the LocalAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalAvailable field is set to the value of the last call.
func (b *StatusApplyConfiguration) WithLocalAvailable(value *LocalAvailableApplyConfiguration) *StatusApplyConfiguration {
	b.LocalAvailable = value
	return b
}
