// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	localartifactsetv1alpha1 "github.com/kubean-io/kubean-api/apis/localartifactset/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LocalArtifactSetLister helps list LocalArtifactSets.
// All objects returned here must be treated as read-only.
type LocalArtifactSetLister interface {
	// List lists all LocalArtifactSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*localartifactsetv1alpha1.LocalArtifactSet, err error)
	// Get retrieves the LocalArtifactSet from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*localartifactsetv1alpha1.LocalArtifactSet, error)
	LocalArtifactSetListerExpansion
}

// localArtifactSetLister implements the LocalArtifactSetLister interface.
type localArtifactSetLister struct {
	listers.ResourceIndexer[*localartifactsetv1alpha1.LocalArtifactSet]
}

// NewLocalArtifactSetLister returns a new LocalArtifactSetLister.
func NewLocalArtifactSetLister(indexer cache.Indexer) LocalArtifactSetLister {
	return &localArtifactSetLister{listers.New[*localartifactsetv1alpha1.LocalArtifactSet](indexer, localartifactsetv1alpha1.Resource("localartifactset"))}
}
